[mypy]
python_version = 3.13
strict = True
plugins = pydantic.mypy
mypy_path = src

[mypy-casbin]
ignore_missing_imports = True
follow_imports = skip

[mypy-casbin.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-casbin_sqlalchemy_adapter.*]
ignore_missing_imports = True
follow_imports = skip
